- summary: |
    Проверка оптимизации и скороти работы. Страница магазина не оптимизирована, низкая скороть работы
   environment: | 
    Яндекс Браузер   23.9.0.2272 (64-bit)
    ОС Windows 10 
   steps-to-reproduce: |
    - открываем DevTools
    - выбираем вкладку "низкопроизводительный телефон"
    - нажимаем "просмотр товара"
    - на вкладке "производительность" в столбце "время" смотрим время загрузки
   expected-result: |
      скорость загрузки не должна превышать 1 сек. 
   actual-result: |
      скорость загрузки более 2 сек.


- summary: |
    Проверка безопасности 2. Отсутствие форм для регистации
   environment: |
    Яндекс Браузер   23.9.0.2272 (64-bit)
    ОС Windows 10 
   steps-to-reproduce: |
    - проверяем на стартовой странице наличие поля для ввода логина
    - проверяем на стартовой странице наличие поля для ввода пароля 
   expected-result: |
      на стартовой странице должны присутствовать поля ввода пароля и логина
   actual-result: |
    на стартовой странице должны отсутствуют поля ввода пароля и логина


- summary: |
     Проверка мобильной версии. Мобильная версия страницы магазина работает не корректно
   environment: |
    Яндекс Браузер   23.9.0.2272 (64-bit)
    ОС Windows 10 
   steps-to-reproduce: |
    - открываем DevTools
    - выбираем на панели инструментов мобильные утройства
    - выбираем парметры iPhone 12 pro
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - выбираем парметры Samsung Galaxy S8+
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - выбираем парметры iPad Mini 
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
   expected-result: |
      На всех открываемых устройствах магазин должен работать без изменения функционала и визуальной картинки
   actual-result: |
      На всех открываемых устройствах страница магазина  работает не корректно- с изменениями функционала и визуальной картинки


    
