- summary: |
    Проверка оптимизации и скороти работы
  requirement: |
    При отсутствии оптимизации скорость работы более 1 сек.
  prerequisites:
    Открыта страница магазина
  test-data: |
    время загрузки
  steps:
    - открываем DevTools
    - выбираем вкладку "низкопроизводительный телефон"
    - нажимаем "просмотр товара"
    - на вкладке "производительность" в столбце "время" смотрим время загрузки
  expected-result: |
    скорость загрузки не должна превышать 1 сек.
    
- summary: |
    Проверка безопасности 1
  requirement: |
    Наличие форм для регистации - Логин и пароль 
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
    наличие поля ввода логина и пароля
  steps:
    - проверяем на стартовой странице наличие поля для ввода логина
    - проверяем на стартовой странице наличие поля для ввода пароля 

  expected-result: |
    на стартовой странице должны присутствовать поля ввода пароля и логина

- summary: |
    Проверка безопасности 2
  requirement: |
    Отсутствие уязвимости при введении JavaScript кода
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
    JavaScript код:<script>alert('Я отправил вам скрипт! Пришлите денег, пожалуйста :(')</script>
   steps:
    - вводим в строку поиска товара JavaScript код:
    - проверяем реакцию магазина с помощью DevTools на введённый JavaScript код
  expected-result: |
    отсутвие измененй при работе магазина

- summary: |
    Проверка поиска по  категории
  requirement: |
    При вводе категории в поле поиска отображаются товары соотвествующие запрашиваемым критериям
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
    категория = laptop 
   steps:
    - вводим в строку поиска товара категорию 
    - проверяем полученные данные поиска
  expected-result: |
    на станице магазина отображены товары соотвествующие запрашиваемой категории

- summary: |
    Проверка поиска по ключевому слову 
  requirement: |
    При вводе ключевого слова  в поле поиска отображаются товары соотвествующие запрашиваемым критериям
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     Ключевое слово =HP
   steps:
    - вводим в строку поиска товара ключевое слово 
    - проверяем полученные данные поиска
  expected-result: |
    на станице магазина отображены товары соотвествующие запрашиваемому ключевому слову


- summary: |
    Проверка возможности фильтровать товары по цене
  requirement: |
    При вводе  параметров цены от и до , происходит фильтрация товаров в указанной ценовой категории.
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     начальное значение цены и конечное значение цены
   steps:
    - вводим в поле "Цена" начальное и конечное значение цены
    - проверяем значения цен отфильтрованных товаров
  expected-result: |
    на станице магазина отображены товары в заданном ценовом диапазоне

- summary: |
    Проверка возможности фильтровать товары по производителю
  requirement: |
    При выборе производителя , происходит фильтрация товаров по указанному производителю.
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     Производитель= Huawei
   steps:
    - выбираем указанного производителя
    - проверяем что товары соотвествуют выбранному производителю
  expected-result: |
    на станице магазина отображены товары производства Huawei


- summary: |
    Проверка возможности фильтровать товары по производителю и цене
  requirement: |
    При выборе производителя и параметров цены от и до , происходит фильтрация товаров по указанному производителю в указанной ценовой категории.
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     Производитель= Huawei, начальное значение цены и конечное значение цены
   steps:
    - выбираем указанного производителя
    - вводим в поле "Цена" начальное и конечное значение цены
    - проверяем что товары соотвествуют выбранному производителю  в указанной ценовой категории
  expected-result: |
    на станице магазина отображены товары производства Huawei и в  заданном ценовом диапазоне


- summary: |
    Проверка мобильной версии
  requirement: |
    Страница магазина должна открываться на мобильных устройствах
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     мобильные устойства различных производителей и размеров
   steps:
    - открываем DevTools
    - выбираем на панели инструментов мобильные утройства
    - выбираем парметры iPhone 12 pro
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - выбираем парметры Samsung Galaxy S8+
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - выбираем парметры iPad Mini 
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
  expected-result: |
    На всех открываемых устройствах магазин должен работать без изменения функционала и визуальной картинки

    
- summary: |
    Проверка совместимости с последними версиями браузеров
  requirement: |
    Страница магазина должна открыватся в последних версиях браузеров
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     последние версии Google Chrome, Firefox, Яндекс браузер
   steps:
    - открываем страницу магазина в браузере Google Chrome
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - открываем страницу магазина в браузере Firefox
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
    - открываем страницу магазина в  Яндекс браузере
    - проверяем функционал магазина (поиск товаров, добавление в корзину, регистрация и.т.д)
  expected-result: |
    Страница магазина должна открыватся на всех браузерах

    
- summary: |
    Проверка  возможности просмотра товаров и просмотра подробной информацию о товаре
  requirement: |
    Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     Товары предсталенные в магазине
   steps:
    - выбираем товар на странице магазина
    - кликаем по названию товара
    - проваливаемся в картчку товара
    - проверяем визуальное тображение товара (фото)
    - проверяем есть ли подробное описание товара
    - повторяем с товарам разных категорий
  expected-result: |
    В карточке товара  существут фото товара и есть его подробное описание


- summary: |
   Проверка возможности добавлять товары в корзину и просматривать содержимое корзины
  requirement: |
    Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  prerequisites:
    Открыта стартовая страница магазина
  test-data: |
     Товары предсталенные в магазине
   steps:
    - выбираем товары на странице магазина
    - добавляем в корзину
    - заходим в корзину
    - проверяем количество товаров в корзине
    - проверяем соотвествие добавленных товаров и товаров нахдящихся в корзине
  expected-result: |
    Товары добавлены в корзину, количество и номенклатура соотвествует выбранным товарам


